# Generated by Django 4.2.5 on 2023-11-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("img_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
