# Generated by Django 4.2.5 on 2023-11-07 12:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("img_app", "0002_image_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="name",
        ),
    ]
